/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ApplyFriend: typeof import('./src/components/ApplyFriend.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseAppBar: typeof import('./src/components/BaseAppBar.vue')['default']
    Blank: typeof import('./src/layouts/blank.vue')['default']
    Cropper: typeof import('./src/components/Cropper.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DefineInput: typeof import('./src/components/DefineInput.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MagicalEffects: typeof import('./src/components/MagicalEffects.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    UserFind: typeof import('./src/components/UserFind.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    Vue3_3Demo: typeof import('./src/components/Vue3_3Demo.vue')['default']
  }
}
